//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasePass.Strings.en_US {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasePass.Strings.en_US.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_AutomaticallyLoggedOut_Message {
            get {
                return ResourceManager.GetString("InfoMessages.AutomaticallyLoggedOut_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_AutomaticallyLoggedOut_Title {
            get {
                return ResourceManager.GetString("InfoMessages.AutomaticallyLoggedOut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_ChangePasswordWrong_Message {
            get {
                return ResourceManager.GetString("InfoMessages,ChangePasswordWrong_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_ChangePasswordWrong_Title {
            get {
                return ResourceManager.GetString("InfoMessages.ChangePasswordWrong_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_DatabaseFileNotFoundAt_Message {
            get {
                return ResourceManager.GetString("InfoMessages.DatabaseFileNotFoundAt_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_DatabaseFileNotFoundAt_Title {
            get {
                return ResourceManager.GetString("InfoMessages.DatabaseFileNotFoundAt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_DatabaseInvalidData_Message {
            get {
                return ResourceManager.GetString("InfoMessages.DatabaseInvalidData_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_DatabaseInvalidData_Title {
            get {
                return ResourceManager.GetString("InfoMessages.DatabaseInvalidData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_DatabaseSaveToFileError_Message {
            get {
                return ResourceManager.GetString("InfoMessages.DatabaseSaveToFileError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_DatabaseSaveToFileError_Title {
            get {
                return ResourceManager.GetString("InfoMessages.DatabaseSaveToFileError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You entered the wrong password.\nPlease try again\n({attempts}/3) ähnelt.
        /// </summary>
        internal static string InfoMessages_EnteredWrongPassword_Message {
            get {
                return ResourceManager.GetString("InfoMessages.EnteredWrongPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong password ähnelt.
        /// </summary>
        internal static string InfoMessages_EnteredWrongPassword_Title {
            get {
                return ResourceManager.GetString("InfoMessages.EnteredWrongPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_ExportDBSuccess_Message {
            get {
                return ResourceManager.GetString("InfoMessages.ExportDBSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_ExportDBSuccess_Title {
            get {
                return ResourceManager.GetString("InfoMessages.ExportDBSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imported data successfully ähnelt.
        /// </summary>
        internal static string InfoMessages_ImportDBSuccess_Message {
            get {
                return ResourceManager.GetString("InfoMessages.ImportDBSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imported successfully ähnelt.
        /// </summary>
        internal static string InfoMessages_ImportDBSuccess_Title {
            get {
                return ResourceManager.GetString("InfoMessages.ImportDBSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not import database, because you&apos;ve entered the wrong password. ähnelt.
        /// </summary>
        internal static string InfoMessages_ImportDBWrongPassword_Message {
            get {
                return ResourceManager.GetString("InfoMessages.ImportDBWrongPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong password ähnelt.
        /// </summary>
        internal static string InfoMessages_ImportDBWrongPassword_Title {
            get {
                return ResourceManager.GetString("InfoMessages.ImportDBWrongPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_NoAccessToPathDatabaseNotLoaded_Message {
            get {
                return ResourceManager.GetString("InfoMessages.NoAccessToPathDatabaseNotLoaded_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_NoAccessToPathDatabaseNotLoaded_Title {
            get {
                return ResourceManager.GetString("InfoMessages.NoAccessToPathDatabaseNotLoaded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_NoAccessToPathDatabaseNotSaved_Message {
            get {
                return ResourceManager.GetString("InfoMessages.NoAccessToPathDatabaseNotSaved_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_NoAccessToPathDatabaseNotSaved_Title {
            get {
                return ResourceManager.GetString("InfoMessages.NoAccessToPathDatabaseNotSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_PasswordsDoNotMatch_Message {
            get {
                return ResourceManager.GetString("InfoMessages.PasswordsDoNotMatch_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_PasswordsDoNotMatch_Title {
            get {
                return ResourceManager.GetString("InfoMessages.PasswordsDoNotMatch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_PasswordTooShort_Message {
            get {
                return ResourceManager.GetString("InfoMessages.PasswordTooShort_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_PasswordTooShort_Title {
            get {
                return ResourceManager.GetString("InfoMessages.PasswordTooShort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_SuccessfullyChangedPassword_Message {
            get {
                return ResourceManager.GetString("InfoMessages.SuccessfullyChangedPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoMessages_SuccessfullyChangedPassword_Title {
            get {
                return ResourceManager.GetString("InfoMessages.SuccessfullyChangedPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You entered the password wrong three times ähnelt.
        /// </summary>
        internal static string InfoMessages_TooManyPasswordAttempts_Message {
            get {
                return ResourceManager.GetString("InfoMessages.TooManyPasswordAttempts_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many attempts ähnelt.
        /// </summary>
        internal static string InfoMessages_TooManyPasswordAttempts_Title {
            get {
                return ResourceManager.GetString("InfoMessages.TooManyPasswordAttempts_Title", resourceCulture);
            }
        }
    }
}
